import type { Metadata } from "next";
import { Inter, Zen_Dots } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const zdots = Zen_Dots({ 
  subsets : ["latin-ext"],
  weight : '400'
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className="bg-blue-950">
      <body className={zdots.className}>{children}</body>
    </html>
  );
}
